### ISSUE TITLE
[Feature Request] Rich Text Block Support

### ISSUE THREAD

**Issue by dmorgan-fa** [CGA1123/slack-ruby-block-kit#184]
Hi @CGA1123, this is a great gem and really simplifies working with Slack Block Kit in a scripted way!

I notice that [rich text block](https://api.slack.com/reference/block-kit/blocks#rich_text) and it's various elements aren't currently supported. I think they're comparatively new and could be quite complicated to support. 

Is this something you're aware of and likely to implement?

Trying to lay something out in a table in Slack is pretty frustrating and the next best solution is using [Rich Text's list](https://app.slack.com/block-kit-builder/T0252T2FN#%7B%22blocks%22:%5B%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22Basic%20bullet%20list%20with%20rich%20elements%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_list%22,%22style%22:%22bullet%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22item%201:%20%22%7D,%7B%22type%22:%22emoji%22,%22name%22:%22basketball%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22item%202:%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22this%20is%20a%20list%20item%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22item%203:%20%22%7D,%7B%22type%22:%22link%22,%22url%22:%22https://slack.com/%22,%22text%22:%22with%20a%20link%22,%22style%22:%7B%22bold%22:true%7D%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22item%204:%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22we%20are%20near%20the%20end%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22item%205:%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22this%20is%20the%20end%22%7D%5D%7D%5D%7D%5D%7D%5D%7D) options.

**Comment by CGA1123** [comment]
Hey @dmorgan-fa -- glad to hear this gem has been of use!

I wasn't aware of the rich text block being added. Looks like a great feature.

I agree, it does seem like there are a lot of new elements that need to be added in order to fully support it, although the complexity itself doesn't seem so high (from a relatively quick scan of the documentation).

I would have very supportive of any contributions moving to implementing this! Carving time out to implement this myself might not meet any timelines that you might have for your use-case though -- a partial implementation including support only for rich-text lists would set a great foundation down for further rich text elements.
